eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka

server:
  port: 8000

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: batch-server
          uri:
            lb://BATCH-SERVER
          predicates:
            - Path=

        - id: alert-service
          uri:
            lb://ALERT-SERVICE
          predicates:
            - Path=/api/alerts/**

        - id: inquiry-service
          uri:
            lb://INQUIRY-SERVICE
          predicates:
            - Path=/api/query/**

logging:
  pattern:
    file: "%-4relative [%thread] %-5level %logger{35} - %msg%n"
  level:
    root: info
    org.hibernate.SQL: debug
  file:
    path: /Users/air/Desktop/project/weather-api/alert-service/src/main/resources/static/log/
  logback:
    rolling policy:
      max-file-size: 500MB
      max-history: 7